### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by liyupeng-ing** [mchengny/RWF2000-Video-Database-for-Violence-Detection#2]
请问可以提供一下预训练的模型吗？

**Comment by mchengny** [comment]
您好，刚刚上传了预训练模型以及简单的使用明，请查阅该仓库的/Models文件夹

**Comment by mchengny** [comment]
> 请问可以提供一下预训练的模型吗？

您好，刚刚上传了预训练模型以及简单的使用明，请查阅该仓库的/Models文件夹

**Comment by sujiongming** [comment]
使用预训练模型的在val上的测试结果为：
predict    0    1
label            
0        174   28
1         26  172
准确度为（174+172）/400=86.5%
对应paper中的哪个模型呢？貌似没看到？
