### ISSUE TITLE
online inference

### ISSUE THREAD

**Issue by liyupeng-ing** [mchengny/RWF2000-Video-Database-for-Violence-Detection#3]
![result_2](https://user-images.githubusercontent.com/11076935/84556240-bb085e00-ad53-11ea-98f8-6586b1736367.gif)
您好，请问还原这种图的代码能提供一下吗？主要是想学习是如何实现在线inference的，因为您训练出来的是一个视频分类器，那么是如何实现图中的在线处理视频的呢？

**Comment by mchengny** [comment]
> ![result_2](https://user-images.githubusercontent.com/11076935/84556240-bb085e00-ad53-11ea-98f8-6586b1736367.gif)
> 您好，请问还原这种图的代码能提供一下吗？主要是想学习是如何实现在线inference的，因为您训练出来的是一个视频分类器，那么是如何实现图中的在线处理视频的呢？

您好，非常抱歉这块的代码是很早之前的了，最近找了找没找到。方法就是把视频分成很多个片段，每个片段进行送入模型一次进行分类。所以你也可以从图中看到，大概是2s才切换一次预测结果。

**Comment by liyupeng-ing** [comment]
好的 ，感谢答复
