### ISSUE TITLE
the pretrained model

### ISSUE THREAD

**Issue by Meggile** [mchengny/RWF2000-Video-Database-for-Violence-Detection#5]
请问您预训练的模型具体是什么网络，vgg resnet 还是mobilenet？可以贴训练后的最优模型吗

**Comment by mchengny** [comment]
> 请问您预训练的模型具体是什么网络，vgg resnet 还是mobilenet？可以贴训练后的最优模型吗

您好，我们的模型是按照论文中的结构从头训练的，只是中间把传统3*3的卷积改成了mobilenet中的depthwise conv和pointwise conv的组合
