### ISSUE TITLE
keras version

### ISSUE THREAD

**Issue by gulinsong** [mchengny/RWF2000-Video-Database-for-Violence-Detection#6]
hello， can you share the version of keras that you used?

**Comment by mchengny** [comment]
> hello， can you share the version of Keras that you used?

Hi, sorry about this problem. Before I made this repo, my GPU server was crashed and re-installed the Linux system.  Therefore it is difficult to figure out the specific version of Keras. One possible version is tf1.12.0, if you successfully run it, would please make a new issue to let others know this? Thanks very much.

**Comment by ayanasser** [comment]
I ran it successfully and those are the requirements I got 
cuda:10.0-cudnn7
Keras (2.3.1)
tensorflow-gpu (1.13.1)
