### ISSUE TITLE
i want to get dataset, but i am in china, SMTP error(554)

### ISSUE THREAD

**Issue by wangpengfei984597422** [mchengny/RWF2000-Video-Database-for-Violence-Detection#7]
i am a student in china, i send a e-mail to you, but my e-mail cannot be sent successfully, the following prompt errors: SMTP error, OPEN: 554 mail-gw-intl-03.oit.duke.edu ESMTP Blocked - see https://ipcheck.proofpoint.com/?ip=202.118.1.203.

i am very eager to get your dataset, what should i do?

**Comment by mchengny** [comment]
> i am a student in china, i send a e-mail to you, but my e-mail cannot be sent successfully, the following prompt errors: SMTP error, OPEN: 554 mail-gw-intl-03.oit.duke.edu ESMTP Blocked - see https://ipcheck.proofpoint.com/?ip=202.118.1.203.
> 
> i am very eager to get your dataset, what should i do?

Hi, please contact me by another e-mail address: 1310708786@qq.com

**Comment by wangpengfei984597422** [comment]
Thank you so much. I have send e-mail for you by my edu email.
