### ISSUE TITLE
预训练模型问题

### ISSUE THREAD

**Issue by sujiongming** [mchengny/RWF2000-Video-Database-for-Violence-Detection#8]
使用预训练模型的在val上的测试结果为：
predict 0 1
label
0 174 28
1 26 172
准确度为（174+172）/400=86.5%
这个结果有问题吗？如果没问题，对应paper中的哪个模型呢？貌似没看到？

**Comment by mchengny** [comment]
> 使用预训练模型的在val上的测试结果为：
> predict 0 1
> label
> 0 174 28
> 1 26 172
> 准确度为（174+172）/400=86.5%
> 这个结果有问题吗？如果没问题，对应paper中的哪个模型呢？貌似没看到？

你好，

对应的就是RGB+Flow综合版的87.25%的模型，因为预训练模型是论文放Arxiv后很久根据issue里要求后加的。后面一年里服务器经历过一次硬盘损坏，因此该模型参数是我又随机跑了一遍得到的。涉及到调参和随机数种子的问题，因此会存在一点点波动。
